// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFIJzZo9ubiaHPepiNin0NJEe8lZOsY5c',
    appId: '1:1069701162286:web:e7a087d772d67ca26f06bf',
    messagingSenderId: '1069701162286',
    projectId: 'railrock-ccb59',
    authDomain: 'railrock-ccb59.firebaseapp.com',
    storageBucket: 'railrock-ccb59.firebasestorage.app',
    measurementId: 'G-GEBSFKRCCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhA18vde7aLgwLq86a1au-9GT51MQTrig',
    appId: '1:1069701162286:android:20717189c95f65486f06bf',
    messagingSenderId: '1069701162286',
    projectId: 'railrock-ccb59',
    storageBucket: 'railrock-ccb59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGcAK5liGByJg-_f6DS12WI4oRVNfROxg',
    appId: '1:1069701162286:ios:e73a8dfa29417a836f06bf',
    messagingSenderId: '1069701162286',
    projectId: 'railrock-ccb59',
    storageBucket: 'railrock-ccb59.firebasestorage.app',
    iosBundleId: 'com.example.railrock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGcAK5liGByJg-_f6DS12WI4oRVNfROxg',
    appId: '1:1069701162286:ios:e73a8dfa29417a836f06bf',
    messagingSenderId: '1069701162286',
    projectId: 'railrock-ccb59',
    storageBucket: 'railrock-ccb59.firebasestorage.app',
    iosBundleId: 'com.example.railrock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFIJzZo9ubiaHPepiNin0NJEe8lZOsY5c',
    appId: '1:1069701162286:web:9240324e256db83e6f06bf',
    messagingSenderId: '1069701162286',
    projectId: 'railrock-ccb59',
    authDomain: 'railrock-ccb59.firebaseapp.com',
    storageBucket: 'railrock-ccb59.firebasestorage.app',
    measurementId: 'G-2202XXG9HV',
  );
}
